In [1]:
import json
#from google.colab import files # solo para google collab
from google.cloud import storage
import pandas as pd
print(storage.__version__)

2.6.0

In [2]:
# google collab
#path_api_key = '/content/extreme-unison-399121-cadd77c555ca.json'

# entorno local
path_api_key = '/Users/manuel/gdrive/prgrmmng/gcloud_api_key/extreme-unison-399121-cadd77c555ca.json'

# extraigo las credenciales para el acceso
service_account_info = json.load(open(path_api_key))

# autorizo el acceso a cloud storage
client_storage = storage.Client.from_service_account_info(service_account_info)

In [3]:
# carga de datos
# unicamente para .py en VM:
#data_gmaps_reviews_norm = pd.read_parquet('gs://1_transform/data_gmaps_reviews_norm.parquet')

# para entorno Google Colab o maquina local:

# cambiar segun bucket
bucket = client_storage.get_bucket('1_transform')

# cambiar segun dataframe
data_blob = bucket.blob('data_gmaps_reviews_norm_county.parquet')
data_gmaps_reviews_county = pd.read_parquet(storage.fileio.BlobReader(data_blob))
data_gmaps_reviews_county.info()
data_gmaps_reviews_county.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1441572 entries, 0 to 1441571
Data columns (total 19 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   gmap_id          1441572 non-null  object
 1   user_id          1441572 non-null  object
 2   user_name        1441572 non-null  object
 3   user_time        1441572 non-null  int64
 4   rating           1441572 non-null  int64
 5   user_text        886694 non-null   object
 6   resp_time        234034 non-null   float64
 7   resp_text        234034 non-null   object
 8   user_time_year   1441572 non-null  int32
 9   user_time_month  1441572 non-null  int32
 10  user_time_day    1441572 non-null  int32
 11  user_time_hms    1441572 non-null  object
 12  resp_time_year   234034 non-null   float64
 13  resp_time_month  234034 non-null   float64
 14  resp_time_day    234034 non-null   float64
 15  resp_time_hms    234034 non-null   object
 16  state_name       1441572 non-null  object
 17  state_code       1441572 non-null  object
 18  county_name      1441572 non-null  object
dtypes: float64(4), int32(3), int64(2), object(10)
memory usage: 192.5+ MB

,gmap_id,user_id,user_name,user_time,rating,user_text,resp_time,resp_text,user_time_year,user_time_month,user_time_day,user_time_hms,resp_time_year,resp_time_month,resp_time_day,resp_time_hms,state_name,state_code,county_name
0,0x88892bb449d44cb3:0x7beaf0b2e3171a49,110771718750038252970,Christian Buckner,1630031374725,2,"No masks, requested curbside and waited 10 min...",NaN,None,2021,8,27,02:29:34.725000,NaN,NaN,NaN,None,alabama,AL,bibb county
1,0x88892bb449d44cb3:0x7beaf0b2e3171a49,110771718750038252970,Christian Buckner,1630031374725,2,"No masks, requested curbside and waited 10 min...",NaN,None,2021,8,27,02:29:34.725000,NaN,NaN,NaN,None,alabama,AL,chilton county