In [16]:
# Librerias
import numpy as np
import pandas as pd
from difflib import SequenceMatcher

In [56]:
# Cargo metadata de gmaps ya filtrado en el etl
df_gmaps = pd.read_csv('C:/Users/54280/Documents/GitHub/proyectogrupal/Pruebas/df_diferencias.csv')
# Cargo business de yeld ya filtrado en el etl
df_business = pd.read_parquet('C:/Users/54280/Documents/GitHub/proyectogrupal/Pruebas/business.parquet')

In [57]:
df_business.head(2)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
index,,,,,,,,,,,,,,
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [58]:
# Genero un df unico para ambos df
df_merged = pd.merge(df_gmaps, df_business, on=['latitude', 'longitude'], how='inner')

In [61]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64629 entries, 3 to 150340
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   64629 non-null  object
 1   name          64629 non-null  object
 2   address       64629 non-null  object
 3   city          64629 non-null  object
 4   state         64629 non-null  object
 5   postal_code   64629 non-null  object
 6   latitude      64629 non-null  float64
 7   longitude     64629 non-null  float64
 8   stars         64629 non-null  float64
 9   review_count  64629 non-null  int64
 10  is_open       64629 non-null  int64
 11  attributes    63752 non-null  object
 12  categories    64629 non-null  object
 13  hours         55293 non-null  object
dtypes: float64(3), int64(2), object(9)
memory usage: 7.4+ MB

In [62]:
df_gmaps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3696 entries, 0 to 3695
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0.1      3696 non-null   int64
 1   Unnamed: 0        3696 non-null   int64
 2   name_x            3691 non-null   object
 3   address_x         3696 non-null   object
 4   gmap_id           3696 non-null   object
 5   description       1173 non-null   object
 6   latitude          3696 non-null   float64
 7   longitude         3696 non-null   float64
 8   category          3696 non-null   object
 9   avg_rating        3696 non-null   float64
 10  num_of_reviews    3696 non-null   int64
 11  hours_x           3349 non-null   object
 12  MISC              3672 non-null   object
 13  state_x           3349 non-null   object
 14  relative_results  2543 non-null   object
 15  url               3696 non-null   object
 16  estado_categoria  3696 non-null   object
 17  business_id       3696 non-null   object
 18  name_y            3696 non-null   object
 19  address_y         3682 non-null   object
 20  city              3696 non-null   object
 21  state_y           3696 non-null   object
 22  postal_code       3696 non-null   int64
 23  stars             3696 non-null   float64
 24  review_count      3696 non-null   int64
 25  is_open           3696 non-null   int64
 26  attributes        3514 non-null   object
 27  categories        3696 non-null   object
 28  hours_y           3105 non-null   object
dtypes: float64(4), int64(6), object(19)
memory usage: 837.5+ KB

In [59]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10352 entries, 0 to 10351
Data columns (total 41 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0.1      10352 non-null  int64
 1   Unnamed: 0        10352 non-null  int64
 2   name_x            10332 non-null  object
 3   address_x         10352 non-null  object
 4   gmap_id           10352 non-null  object
 5   description       4055 non-null   object
 6   latitude          10352 non-null  float64
 7   longitude         10352 non-null  float64
 8   category          10352 non-null  object
 9   avg_rating        10352 non-null  float64
 10  num_of_reviews    10352 non-null  int64
 11  hours_x           9436 non-null   object
 12  MISC              10312 non-null  object
 13  state_x           9436 non-null   object
 14  relative_results  7711 non-null   object
 15  url               10352 non-null  object
 16  estado_categoria  10352 non-null  object
 17  business_id_x     10352 non-null  object
 18  name_y            10352 non-null  object
 19  address_y         10345 non-null  object
 20  city_x            10352 non-null  object
 21  state_y           10352 non-null  object
 22  postal_code_x     10352 non-null  int64
 23  stars_x           10352 non-null  float64
 24  review_count_x    10352 non-null  int64
 25  is_open_x         10352 non-null  int64
 26  attributes_x      9714 non-null   object
 27  categories_x      10352 non-null  object
 28  hours_y           8445 non-null   object
 29  business_id_y     10352 non-null  object
 30  name              10352 non-null  object
 31  address           10352 non-null  object
 32  city_y            10352 non-null  object
 33  state             10352 non-null  object
 34  postal_code_y     10352 non-null  object
 35  stars_y           10352 non-null  float64
 36  review_count_y    10352 non-null  int64
 37  is_open_y         10352 non-null  int64
 38  attributes_y      9948 non-null   object
 39  categories_y      10352 non-null  object
 40  hours             8576 non-null   object
dtypes: float64(5), int64(8), object(28)
memory usage: 3.2+ MB

In [8]:
# Comparo diferencias en nombres 
son_iguales = df_merged['name_x'].equals(df_merged['name_y'])

In [9]:
# Filtro filas diferentes en nombres
filas_diferentes = df_merged[df_merged['name_x'] != df_merged['name_y']]

In [13]:
filas_diferentes.head(2)

,Unnamed: 0.1,Unnamed: 0,name_x,address_x,gmap_id,description,latitude,longitude,category,avg_rating,...,address,city_y,state,postal_code_y,stars_y,review_count_y,is_open_y,attributes_y,categories_y,hours
0,2,17109,Brother Doug's Pizza Cafe,"Brother Doug's Pizza Cafe, 11005 Allisonville ...",0x8814b30f4c7d5b31:0x1e81e6866abca4b5,NaN,39.949625,-86.041843,pizza restaurant,4.8,...,11005 Allisonville Rd,Fishers,MO,46038,4.0,44,0,"{'NoiseLevel': 'u'quiet'', 'WiFi': 'u'free'', ...","Restaurants, Pizza","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
1,3,17109,Brother Doug's Pizza Cafe,"Brother Doug's Pizza Cafe, 11005 Allisonville ...",0x8814b30f4c7d5b31:0x1e81e6866abca4b5,NaN,39.949625,-86.041843,takeout restaurant,4.8,...,11005 Allisonville Rd,Fishers,MO,46038,4.0,44,0,"{'NoiseLevel': 'u'quiet'', 'WiFi': 'u'free'', ...","Restaurants, Pizza","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."

In [14]:
# Filtrar las filas donde name_x y name_y son diferentes
filas_diferentes = df_merged[df_merged['name_x'] != df_merged['name_y']]

# Mostrar las columnas 'name_x' y 'name_y' junto con el índice
columnas_deseadas = ['name_x', 'name_y']
resultados = filas_diferentes[columnas_deseadas]

# Imprimir los resultados
print(resultados)

                                         name_x  \
0                     Brother Doug's Pizza Cafe
1                     Brother Doug's Pizza Cafe
2                     Brother Doug's Pizza Cafe
3                     Brother Doug's Pizza Cafe
4                                         Pomme
...                                         ...
10347              Rositas Cocina Original Mxcn
10348  El Paso Mexican Grill On Magazine Street
10349                                 Wing Shop
10350                                 Wing Shop
10351                         RH Nashville Café

                                        name_y
0                    Brother Doug's Pizza Café
1                    Brother Doug's Pizza Café
2                    Brother Doug's Pizza Café
3                    Brother Doug's Pizza Café
4                             Pomme Restaurant
...                                        ...
10347               Sonny's Italian Restaurant
10348                    El Paso Mexican Grill
10349                            Rocket Burger
10350                            Rocket Burger
10351  RH Courtyard Restaurant at RH Nashville

[10352 rows x 2 columns]

In [15]:
resultados

,name_x,name_y
0,Brother Doug's Pizza Cafe,Brother Doug's Pizza Café
1,Brother Doug's Pizza Cafe,Brother Doug's Pizza Café
2,Brother Doug's Pizza Cafe,Brother Doug's Pizza Café
3,Brother Doug's Pizza Cafe,Brother Doug's Pizza Café
4,Pomme,Pomme Restaurant
...,...,...
10347,Rositas Cocina Original Mxcn,Sonny's Italian Restaurant
10348,El Paso Mexican Grill On Magazine Street,El Paso Mexican Grill
10349,Wing Shop,Rocket Burger
10350,Wing Shop,Rocket Burger
10351,RH Nashville Café,RH Courtyard Restaurant at RH Nashville

In [26]:
# Función para calcular la similitud entre dos cadenas
def similarity(s1, s2):
    if isinstance(s1, str) and isinstance(s2, str):
        return str(SequenceMatcher(None, s1, s2).ratio())
    else:
        return 0.0  # Devolver 0.0 si no son cadenas

In [28]:
# Comapraro la similitud de los nombres y guarda en una nueva columna
df_merged['similarity'] = df_merged.apply(lambda row: similarity(row['name_x'], row['name_y']), axis=1)

In [45]:
# Veo el df
df_merged.head(2)

,Unnamed: 0.1,Unnamed: 0,name_x,address_x,gmap_id,description,latitude,longitude,category,avg_rating,...,city_y,state,postal_code_y,stars_y,review_count_y,is_open_y,attributes_y,categories_y,hours,similarity
0,2,17109,Brother Doug's Pizza Cafe,"Brother Doug's Pizza Cafe, 11005 Allisonville ...",0x8814b30f4c7d5b31:0x1e81e6866abca4b5,NaN,39.949625,-86.041843,pizza restaurant,4.8,...,Fishers,MO,46038,4.0,44,0,"{'NoiseLevel': 'u'quiet'', 'WiFi': 'u'free'', ...","Restaurants, Pizza","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...",0.96
1,3,17109,Brother Doug's Pizza Cafe,"Brother Doug's Pizza Cafe, 11005 Allisonville ...",0x8814b30f4c7d5b31:0x1e81e6866abca4b5,NaN,39.949625,-86.041843,takeout restaurant,4.8,...,Fishers,MO,46038,4.0,44,0,"{'NoiseLevel': 'u'quiet'', 'WiFi': 'u'free'', ...","Restaurants, Pizza","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...",0.96

In [31]:
# Voy a reemplazar los nombres de la columna name_y con los de la nombres de la columna name_x cuando la similitud sea mayor a 0.7

# Defino un umbral de similitud
umbral_similitud = 0.7

# Reemplazo los valores en 'name_y' con 'name_x' cuando la similitud sea mayor o igual al umbral
df_merged['name_y'] = df_merged.apply(lambda row: row['name_x'] if float(row['similarity']) >= umbral_similitud else row['name_y'], axis=1)

In [42]:
# Filtro las filas donde name_x y name_y son diferentes
filas_diferentes = df_merged[df_merged['name_x'] != df_merged['name_y']]

# Mostro las columnas 'name_x' y 'name_y' junto con el índice
columnas_deseadas = ['name_x', 'name_y','similarity']
resultados = filas_diferentes[columnas_deseadas]

# Veo los resultados
resultados.head(50)

,name_x,name_y,similarity
4,Pomme,Pomme Restaurant,0.47619047619047616
5,Pomme,Pomme Restaurant,0.47619047619047616
6,Pomme,Pomme Restaurant,0.47619047619047616
7,Pomme,Pomme Restaurant,0.47619047619047616
8,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
9,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
10,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
11,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
12,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
13,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
14,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
15,AK Preps & Bakery,AK PREPS AND BAKERY,0.3888888888888889
16,Sweet Life Cakes and Desserts,Bakery 519,0.20512820512820512
17,Sweet Life Cakes and Desserts,Bakery 519,0.20512820512820512
18,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
19,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
20,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
21,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
22,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
23,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
24,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
25,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
26,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
27,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
28,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
29,Clean Juice,Cold Stone Creamery,0.3333333333333333
30,Clean Juice,Cold Stone Creamery,0.3333333333333333
31,Clean Juice,Cold Stone Creamery,0.3333333333333333
32,Clean Juice,Cold Stone Creamery,0.3333333333333333
33,Clean Juice,Cold Stone Creamery,0.3333333333333333
34,Clean Juice,Cold Stone Creamery,0.3333333333333333
35,Clean Juice,Cold Stone Creamery,0.3333333333333333
36,Clean Juice,Cold Stone Creamery,0.3333333333333333
37,Clean Juice,Cold Stone Creamery,0.3333333333333333
38,Clean Juice,Cold Stone Creamery,0.3333333333333333
39,Clean Juice,Cold Stone Creamery,0.3333333333333333
40,Clean Juice,Cold Stone Creamery,0.3333333333333333
42,AVO TACO,Stokehold Restaurant,0.07142857142857142
43,Wanda BYOB,Braise 116,0.2
44,Wanda BYOB,Braise 116,0.2
45,Central BBQ (Hillsboro),Central BBQ,0.6470588235294118
46,Central BBQ (Hillsboro),Central BBQ,0.6470588235294118
47,Central BBQ (Hillsboro),Sportsman's Grille,0.24390243902439024
48,Central BBQ (Hillsboro),Sportsman's Grille,0.24390243902439024
49,WellVue Nutrition,Bellevue Tanning Club,0.3684210526315789
51,WellVue Nutrition,MyEyeDr,0.16666666666666666
52,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
53,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
54,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
55,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693

Veo que la escala que tome es demasiado grande en 0.7 ya que hasta el 0.38 tenemos restaurant que tiene casi los mismo nombres y no entran por tener un adicional en el nombre o estar en mayusculas. Vuelvo a ajustar el umbral.

In [43]:
# Defino un umbral de similitud
umbral_similitud = 0.38

# Reemplazo los valores en 'name_y' con 'name_x' cuando la similitud sea mayor o igual al umbral
df_merged['name_y'] = df_merged.apply(lambda row: row['name_x'] if float(row['similarity']) >= umbral_similitud else row['name_y'], axis=1)

In [46]:
# Filtro las filas donde name_x y name_y son diferentes
filas_diferentes = df_merged[df_merged['name_x'] != df_merged['name_y']]

# Mostro las columnas 'name_x' y 'name_y' junto con el índice
columnas_deseadas = ['name_x', 'name_y','similarity']
resultados = filas_diferentes[columnas_deseadas]

# Veo los resultados
resultados.head(50)

,name_x,name_y,similarity
16,Sweet Life Cakes and Desserts,Bakery 519,0.20512820512820512
17,Sweet Life Cakes and Desserts,Bakery 519,0.20512820512820512
18,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
19,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
20,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
21,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
22,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
23,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
24,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
25,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
26,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
27,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
28,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
29,Clean Juice,Cold Stone Creamery,0.3333333333333333
30,Clean Juice,Cold Stone Creamery,0.3333333333333333
31,Clean Juice,Cold Stone Creamery,0.3333333333333333
32,Clean Juice,Cold Stone Creamery,0.3333333333333333
33,Clean Juice,Cold Stone Creamery,0.3333333333333333
34,Clean Juice,Cold Stone Creamery,0.3333333333333333
35,Clean Juice,Cold Stone Creamery,0.3333333333333333
36,Clean Juice,Cold Stone Creamery,0.3333333333333333
37,Clean Juice,Cold Stone Creamery,0.3333333333333333
38,Clean Juice,Cold Stone Creamery,0.3333333333333333
39,Clean Juice,Cold Stone Creamery,0.3333333333333333
40,Clean Juice,Cold Stone Creamery,0.3333333333333333
42,AVO TACO,Stokehold Restaurant,0.07142857142857142
43,Wanda BYOB,Braise 116,0.2
44,Wanda BYOB,Braise 116,0.2
47,Central BBQ (Hillsboro),Sportsman's Grille,0.24390243902439024
48,Central BBQ (Hillsboro),Sportsman's Grille,0.24390243902439024
49,WellVue Nutrition,Bellevue Tanning Club,0.3684210526315789
51,WellVue Nutrition,MyEyeDr,0.16666666666666666
52,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
53,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
54,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
55,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
56,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
57,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
58,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
59,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
60,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
61,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
62,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
63,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
64,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
65,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
66,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
67,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
68,Sekushi Japanese Sushi and Raw Bar,Snowrolls,0.09302325581395349
69,Sekushi Japanese Sushi and Raw Bar,Snowrolls,0.09302325581395349

In [47]:
resultados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8556 entries, 16 to 10350
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name_x      8536 non-null   object
 1   name_y      8556 non-null   object
 2   similarity  8556 non-null   object
dtypes: object(3)
memory usage: 267.4+ KB

Tomo nocion que tenemos datos faltantes en name_x pero no en name_y con lo cual lo voy a explorar

In [48]:
# Verifico qué filas en 'name_x' tienen valores nulos
filas_con_nulos = df_merged[df_merged['name_x'].isnull()]

Voy a reemplazar los valores faltantes de name_x con los de name_y

In [50]:
# Reemplazar los valores nulos en 'name_x' con los valores de 'name_y'
df_merged['name_x'].fillna(df_merged['name_y'], inplace=True)

In [52]:
# Filtro las filas donde name_x y name_y son diferentes
filas_diferentes = df_merged[df_merged['name_x'] != df_merged['name_y']]

# Mostro las columnas 'name_x' y 'name_y' junto con el índice
columnas_deseadas = ['name_x', 'name_y','similarity']
resultados = filas_diferentes[columnas_deseadas]

# Veo los resultados
resultados.head(50)

,name_x,name_y,similarity
16,Sweet Life Cakes and Desserts,Bakery 519,0.20512820512820512
17,Sweet Life Cakes and Desserts,Bakery 519,0.20512820512820512
18,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
19,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
20,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
21,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
22,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
23,Ricardo's Mexican Restaurant & Taqueria,Dana's Cafe,0.2
24,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
25,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
26,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
27,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
28,Family Traditions Restaurant,Dana's Cafe,0.2564102564102564
29,Clean Juice,Cold Stone Creamery,0.3333333333333333
30,Clean Juice,Cold Stone Creamery,0.3333333333333333
31,Clean Juice,Cold Stone Creamery,0.3333333333333333
32,Clean Juice,Cold Stone Creamery,0.3333333333333333
33,Clean Juice,Cold Stone Creamery,0.3333333333333333
34,Clean Juice,Cold Stone Creamery,0.3333333333333333
35,Clean Juice,Cold Stone Creamery,0.3333333333333333
36,Clean Juice,Cold Stone Creamery,0.3333333333333333
37,Clean Juice,Cold Stone Creamery,0.3333333333333333
38,Clean Juice,Cold Stone Creamery,0.3333333333333333
39,Clean Juice,Cold Stone Creamery,0.3333333333333333
40,Clean Juice,Cold Stone Creamery,0.3333333333333333
42,AVO TACO,Stokehold Restaurant,0.07142857142857142
43,Wanda BYOB,Braise 116,0.2
44,Wanda BYOB,Braise 116,0.2
47,Central BBQ (Hillsboro),Sportsman's Grille,0.24390243902439024
48,Central BBQ (Hillsboro),Sportsman's Grille,0.24390243902439024
49,WellVue Nutrition,Bellevue Tanning Club,0.3684210526315789
51,WellVue Nutrition,MyEyeDr,0.16666666666666666
52,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
53,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
54,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
55,Sekushi Japanese Sushi and Raw Bar,Godiva Chocolatier,0.07692307692307693
56,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
57,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
58,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
59,Sekushi Japanese Sushi and Raw Bar,Victoria's Secret,0.11764705882352941
60,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
61,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
62,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
63,Sekushi Japanese Sushi and Raw Bar,Venetian Interiors & Design,0.26229508196721313
64,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
65,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
66,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
67,Sekushi Japanese Sushi and Raw Bar,Bose Store,0.22727272727272727
68,Sekushi Japanese Sushi and Raw Bar,Snowrolls,0.09302325581395349
69,Sekushi Japanese Sushi and Raw Bar,Snowrolls,0.09302325581395349

In [53]:
resultados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8536 entries, 16 to 10350
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name_x      8536 non-null   object
 1   name_y      8536 non-null   object
 2   similarity  8536 non-null   object
dtypes: object(3)
memory usage: 266.8+ KB

Investigando las diferencias encuentro que varios de los casos corresponden a tiendas que estan en un shopping y algunos restauranes estan en la base de yelp y otros en la gmpas con lo cual procedo a eliminarlos ya que no representan un valor que nos modifique a los analisis que vamos a hacer