In [1]:
import json
#from google.colab import files # solo para google collab
from google.cloud import storage
import pandas as pd
print(storage.__version__)

2.6.0

In [2]:
# google collab
#path_api_key = '/content/extreme-unison-399121-cadd77c555ca.json'

# entorno local
path_api_key = '/Users/manuel/gdrive/prgrmmng/gcloud_api_key/extreme-unison-399121-cadd77c555ca.json'

# extraigo las credenciales para el acceso
service_account_info = json.load(open(path_api_key))

# autorizo el acceso a cloud storage
client_storage = storage.Client.from_service_account_info(service_account_info)

In [3]:
# carga de datos
# para entorno Google Colab o maquina local:

# cambiar segun bucket
bucket = client_storage.get_bucket('1_transform')

# cambiar segun dataframe
data_blob = bucket.blob('business_metadata_filtrado.parquet')
data_business_metadata = pd.read_parquet(storage.fileio.BlobReader(data_blob))
data_business_metadata.info()
data_business_metadata.head(2)

<class 'pandas.core.frame.DataFrame'>
Index: 335844 entries, 0 to 61680
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   business_id             335844 non-null  object
 1   name                    335844 non-null  object
 2   address                 334362 non-null  object
 3   description             113470 non-null  object
 4   latitude                335844 non-null  Float64
 5   longitude               335844 non-null  Float64
 6   categories              335844 non-null  object
 7   rating_historico        335844 non-null  Float64
 8   review_count_historico  335844 non-null  Int64
 9   price                   148685 non-null  object
 10  hours-state_cat         274163 non-null  object
 11  attributes              331231 non-null  object
 12  codigo_postal_zcta      335844 non-null  object
 13  us_continente           335844 non-null  int64
 14  state_name              335843 non-null  object
 15  state_code              335843 non-null  object
dtypes: Float64(3), Int64(1), int64(1), object(11)
memory usage: 44.8+ MB

,business_id,name,address,description,latitude,longitude,categories,rating_historico,review_count_historico,price,hours-state_cat,attributes,codigo_postal_zcta,us_continente,state_name,state_code
0,0x0:0x2ab217fc59211262,Sidelines Grille,"Sidelines Grille, 3405 Busbee Dr NW, Kennesaw,...",None,34.034708,-84.575423,restaurant,2.3,3,None,Specific Hours,"{'AcceptsInsurance': None, 'Accessibility': ['...",30144,1,georgia,GA
1,0x1412bcfc0336fce9:0x33da3c68ef2176ac,Aztlan Foods Corp,"Aztlan Foods Corp, 9110 NW 106th St, Medley, F...",None,25.869479,-80.347611,food products supplier,4.7,8,None,Open,None,33178,1,florida,FL

In [14]:
data_business_kpi_sindefinir = data_business_metadata.drop(columns=["attributes"]).copy()
data_business_kpi_sindefinir[data_business_kpi_sindefinir.duplicated(keep=False)]

,business_id,name,address,description,latitude,longitude,categories,rating_historico,review_count_historico,price,hours-state_cat,codigo_postal_zcta,us_continente,state_name,state_code
5,0x146c6711a70d7991:0xe478335f760c8ccc,Bar 91,"Bar 91, 400 Ave of the Champions, Palm Beach G...",None,26.828991,-80.141201,restaurant,3.9,8,None,Open,33418,1,florida,FL
6,0x146c6711a70d7991:0xe478335f760c8ccc,Bar 91,"Bar 91, 400 Ave of the Champions, Palm Beach G...",None,26.828991,-80.141201,restaurant,3.9,8,None,Open,33418,1,florida,FL
7,0x146c6711a70d7991:0xe478335f760c8ccc,Bar 91,"Bar 91, 400 Ave of the Champions, Palm Beach G...",None,26.828991,-80.141201,restaurant,3.9,8,None,Open,33418,1,florida,FL
8,0x146c6711a70d7991:0xe478335f760c8ccc,Bar 91,"Bar 91, 400 Ave of the Champions, Palm Beach G...",None,26.828991,-80.141201,restaurant,3.9,8,None,Open,33418,1,florida,FL
101,0x4ca8ad3fffffffa1:0x14e63dd5f68adbda,Shell,"Shell, 529 US-1, Pembroke, ME 04666",None,44.952339,-67.174437,restaurant,4.5,8,$$,Open,04666,1,maine,ME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273201,0x89e8311761d696e5:0xdcd22b9e69edba24,Dunkin',"Dunkin', 205 Wheeler Rd, Hauppauge, NY 11788",Long-running chain serving signature breakfast...,40.803367,-73.212653,breakfast restaurant,3.9,16,$,Open,11788,1,new york,NY
273202,0x89e8311761d696e5:0xdcd22b9e69edba24,Dunkin',"Dunkin', 205 Wheeler Rd, Hauppauge, NY 11788",Long-running chain serving signature breakfast...,40.803367,-73.212653,fast food restaurant,3.9,16,$,Open,11788,1,new york,NY
273203,0x89e8311761d696e5:0xdcd22b9e69edba24,Dunkin',"Dunkin', 205 Wheeler Rd, Hauppauge, NY 11788",Long-running chain serving signature breakfast...,40.803367,-73.212653,fast food restaurant,3.9,16,$,Open,11788,1,new york,NY
273204,0x89e8311761d696e5:0xdcd22b9e69edba24,Dunkin',"Dunkin', 205 Wheeler Rd, Hauppauge, NY 11788",Long-running chain serving signature breakfast...,40.803367,-73.212653,fast food restaurant,3.9,16,$,Open,11788,1,new york,NY
273205,0x89e8311761d696e5:0xdcd22b9e69edba24,Dunkin',"Dunkin', 205 Wheeler Rd, Hauppauge, NY 11788",Long-running chain serving signature breakfast...,40.803367,-73.212653,fast food restaurant,3.9,16,$,Open,11788,1,new york,NY